//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Input/ToolControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ToolControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ToolControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ToolControls"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""06fca0a3-9828-4152-94ca-5019a9b2d7a9"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""e011bd6c-039a-420f-84b7-9f6c9ced65ed"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rise&Fall"",
                    ""type"": ""Value"",
                    ""id"": ""503e91aa-6a37-4c24-8a77-539ac95c888a"",
                    ""expectedControlType"": ""Double"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ControlCamera"",
                    ""type"": ""Button"",
                    ""id"": ""a5d0b55b-c2e9-48c7-8a1c-4c8a5f471ab9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrabItem"",
                    ""type"": ""Button"",
                    ""id"": ""2c81db37-a51c-4e2f-8208-964b6ae2a5c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drag"",
                    ""type"": ""Value"",
                    ""id"": ""2568c1c5-dbd4-4a19-b3f7-97c28b2c9797"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SpawnMarker"",
                    ""type"": ""Button"",
                    ""id"": ""410032fb-5681-4690-8438-4d9442fd3c09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DragZ"",
                    ""type"": ""Value"",
                    ""id"": ""5070899f-e4a7-419a-8c45-4a67d0bd5a52"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3a1f79a8-8f51-4131-acc7-48182d9173ee"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse&Keyboard"",
                    ""action"": ""GrabItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9116c213-13f6-4668-ac2f-1ca51b0cd5c9"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse&Keyboard"",
                    ""action"": ""Drag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50fb44c3-cfaa-4549-b8d8-6c0e2f09a16d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse&Keyboard"",
                    ""action"": ""ControlCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""4f9b6205-de40-42c2-9a86-5f4d7e43b75e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0dfd28f8-11c1-4475-9a93-2ce1d6a13dbe"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse&Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c883f94d-0e90-42d1-a2bc-fd260aa74de6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse&Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2373d4b3-dd38-414d-a8ef-da41c5b6253b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse&Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cac6ae82-2610-465d-a7ac-e7166941f72e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse&Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a9248472-81c9-411e-a5fa-e5b5a53b7cff"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnMarker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b17923f3-2838-4e14-9113-ef6b77e585cc"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""a2d908ed-0952-40a7-802d-c3f0f3d7fa91"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rise&Fall"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f52a7b1f-db30-415a-bb53-ac00c0110346"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rise&Fall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""17e7ecaa-5169-42ff-b72a-c08fa0c077cf"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rise&Fall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse&Keyboard"",
            ""bindingGroup"": ""Mouse&Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_Movement = m_Default.FindAction("Movement", throwIfNotFound: true);
        m_Default_RiseFall = m_Default.FindAction("Rise&Fall", throwIfNotFound: true);
        m_Default_ControlCamera = m_Default.FindAction("ControlCamera", throwIfNotFound: true);
        m_Default_GrabItem = m_Default.FindAction("GrabItem", throwIfNotFound: true);
        m_Default_Drag = m_Default.FindAction("Drag", throwIfNotFound: true);
        m_Default_SpawnMarker = m_Default.FindAction("SpawnMarker", throwIfNotFound: true);
        m_Default_DragZ = m_Default.FindAction("DragZ", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private IDefaultActions m_DefaultActionsCallbackInterface;
    private readonly InputAction m_Default_Movement;
    private readonly InputAction m_Default_RiseFall;
    private readonly InputAction m_Default_ControlCamera;
    private readonly InputAction m_Default_GrabItem;
    private readonly InputAction m_Default_Drag;
    private readonly InputAction m_Default_SpawnMarker;
    private readonly InputAction m_Default_DragZ;
    public struct DefaultActions
    {
        private @ToolControls m_Wrapper;
        public DefaultActions(@ToolControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Default_Movement;
        public InputAction @RiseFall => m_Wrapper.m_Default_RiseFall;
        public InputAction @ControlCamera => m_Wrapper.m_Default_ControlCamera;
        public InputAction @GrabItem => m_Wrapper.m_Default_GrabItem;
        public InputAction @Drag => m_Wrapper.m_Default_Drag;
        public InputAction @SpawnMarker => m_Wrapper.m_Default_SpawnMarker;
        public InputAction @DragZ => m_Wrapper.m_Default_DragZ;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void SetCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMovement;
                @RiseFall.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRiseFall;
                @RiseFall.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRiseFall;
                @RiseFall.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRiseFall;
                @ControlCamera.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnControlCamera;
                @ControlCamera.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnControlCamera;
                @ControlCamera.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnControlCamera;
                @GrabItem.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnGrabItem;
                @GrabItem.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnGrabItem;
                @GrabItem.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnGrabItem;
                @Drag.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnDrag;
                @Drag.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnDrag;
                @Drag.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnDrag;
                @SpawnMarker.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSpawnMarker;
                @SpawnMarker.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSpawnMarker;
                @SpawnMarker.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSpawnMarker;
                @DragZ.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnDragZ;
                @DragZ.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnDragZ;
                @DragZ.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnDragZ;
            }
            m_Wrapper.m_DefaultActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @RiseFall.started += instance.OnRiseFall;
                @RiseFall.performed += instance.OnRiseFall;
                @RiseFall.canceled += instance.OnRiseFall;
                @ControlCamera.started += instance.OnControlCamera;
                @ControlCamera.performed += instance.OnControlCamera;
                @ControlCamera.canceled += instance.OnControlCamera;
                @GrabItem.started += instance.OnGrabItem;
                @GrabItem.performed += instance.OnGrabItem;
                @GrabItem.canceled += instance.OnGrabItem;
                @Drag.started += instance.OnDrag;
                @Drag.performed += instance.OnDrag;
                @Drag.canceled += instance.OnDrag;
                @SpawnMarker.started += instance.OnSpawnMarker;
                @SpawnMarker.performed += instance.OnSpawnMarker;
                @SpawnMarker.canceled += instance.OnSpawnMarker;
                @DragZ.started += instance.OnDragZ;
                @DragZ.performed += instance.OnDragZ;
                @DragZ.canceled += instance.OnDragZ;
            }
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    private int m_MouseKeyboardSchemeIndex = -1;
    public InputControlScheme MouseKeyboardScheme
    {
        get
        {
            if (m_MouseKeyboardSchemeIndex == -1) m_MouseKeyboardSchemeIndex = asset.FindControlSchemeIndex("Mouse&Keyboard");
            return asset.controlSchemes[m_MouseKeyboardSchemeIndex];
        }
    }
    public interface IDefaultActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRiseFall(InputAction.CallbackContext context);
        void OnControlCamera(InputAction.CallbackContext context);
        void OnGrabItem(InputAction.CallbackContext context);
        void OnDrag(InputAction.CallbackContext context);
        void OnSpawnMarker(InputAction.CallbackContext context);
        void OnDragZ(InputAction.CallbackContext context);
    }
}
